#!/usr/bin/env python3
import os, json, datetime, webbrowser, subprocess

DSA_FOLDER = r"C:\Users\Sheshandra Reddy\OneDrive\Desktop\dsa-practice"
README_PATH = os.path.join(DSA_FOLDER, "README.md")
PROGRESS_FILE = os.path.join(DSA_FOLDER, ".progress.json")

PROBLEMS = {
    1:  {"name":"Two Sum","difficulty":"Easy","topic":"HashMap","url":"https://leetcode.com/problems/two-sum","filename":"two_sum.py","solution":'''from typing import List\n\nclass Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        seen = {}\n        for i, num in enumerate(nums):\n            complement = target - num\n            if complement in seen:\n                return [seen[complement], i]\n            seen[num] = i''',"explanation":"\n  PATTERN: HashMap\n  - For each number, check if its complement (target-num) was seen before\n  - If yes return indices, if no store and continue\n  TIME: O(n) | SPACE: O(n)"},
    2:  {"name":"Valid Parentheses","difficulty":"Easy","topic":"Stack","url":"https://leetcode.com/problems/valid-parentheses","filename":"valid_parentheses.py","solution":'''class Solution:\n    def isValid(self, s: str) -> bool:\n        stack = []\n        pairs = {")": "(", "}": "{", "]": "["}\n        for char in s:\n            if char in "({[":\n                stack.append(char)\n            elif stack and stack[-1] == pairs[char]:\n                stack.pop()\n            else:\n                return False\n        return len(stack) == 0''',"explanation":"\n  PATTERN: Stack\n  - Push opening brackets, pop when closing matches\n  - Stack must be empty at end\n  TIME: O(n) | SPACE: O(n)"},
    3:  {"name":"Best Time to Buy and Sell Stock","difficulty":"Easy","topic":"Array","url":"https://leetcode.com/problems/best-time-to-buy-and-sell-stock","filename":"best_time_stock.py","solution":'''from typing import List\n\nclass Solution:\n    def maxProfit(self, prices: List[int]) -> int:\n        min_price = prices[0]\n        max_profit = 0\n        for price in prices[1:]:\n            min_price = min(min_price, price)\n            max_profit = max(max_profit, price - min_price)\n        return max_profit''',"explanation":"\n  PATTERN: Min/Max Tracking\n  - Track minimum price and maximum profit as you go\n  TIME: O(n) | SPACE: O(1)"},
    4:  {"name":"Contains Duplicate","difficulty":"Easy","topic":"HashSet","url":"https://leetcode.com/problems/contains-duplicate","filename":"contains_duplicate.py","solution":'''from typing import List\n\nclass Solution:\n    def containsDuplicate(self, nums: List[int]) -> bool:\n        seen = set()\n        for num in nums:\n            if num in seen:\n                return True\n            seen.add(num)\n        return False''',"explanation":"\n  PATTERN: HashSet\n  - Track seen numbers, return True if seen again\n  TIME: O(n) | SPACE: O(n)"},
    5:  {"name":"Maximum Subarray","difficulty":"Easy","topic":"Kadane's Algorithm","url":"https://leetcode.com/problems/maximum-subarray","filename":"maximum_subarray.py","solution":'''from typing import List\n\nclass Solution:\n    def maxSubArray(self, nums: List[int]) -> int:\n        current_sum = nums[0]\n        max_sum = nums[0]\n        for num in nums[1:]:\n            current_sum = max(num, current_sum + num)\n            max_sum = max(max_sum, current_sum)\n        return max_sum''',"explanation":"\n  PATTERN: Kadane's Algorithm\n  - At each step: start fresh OR extend previous sum\n  TIME: O(n) | SPACE: O(1)"},
    6:  {"name":"Reverse Linked List","difficulty":"Easy","topic":"Linked List","url":"https://leetcode.com/problems/reverse-linked-list","filename":"reverse_linked_list.py","solution":'''class Solution:\n    def reverseList(self, head):\n        prev = None\n        curr = head\n        while curr:\n            next_node = curr.next\n            curr.next = prev\n            prev = curr\n            curr = next_node\n        return prev''',"explanation":"\n  PATTERN: Pointer Manipulation\n  - Use prev, curr, next to reverse pointers one by one\n  TIME: O(n) | SPACE: O(1)"},
    7:  {"name":"Climbing Stairs","difficulty":"Easy","topic":"Dynamic Programming","url":"https://leetcode.com/problems/climbing-stairs","filename":"climbing_stairs.py","solution":'''class Solution:\n    def climbStairs(self, n: int) -> int:\n        if n <= 2:\n            return n\n        prev2, prev1 = 1, 2\n        for _ in range(3, n + 1):\n            current = prev1 + prev2\n            prev2 = prev1\n            prev1 = current\n        return prev1''',"explanation":"\n  PATTERN: Fibonacci\n  - Ways(n) = Ways(n-1) + Ways(n-2)\n  TIME: O(n) | SPACE: O(1)"},
    8:  {"name":"Merge Two Sorted Lists","difficulty":"Easy","topic":"Linked List","url":"https://leetcode.com/problems/merge-two-sorted-lists","filename":"merge_two_lists.py","solution":'''class Solution:\n    def mergeTwoLists(self, list1, list2):\n        dummy = type(list1)(0)\n        current = dummy\n        while list1 and list2:\n            if list1.val <= list2.val:\n                current.next = list1\n                list1 = list1.next\n            else:\n                current.next = list2\n                list2 = list2.next\n            current = current.next\n        current.next = list1 if list1 else list2\n        return dummy.next''',"explanation":"\n  PATTERN: Dummy Node\n  - Compare heads, attach smaller, advance that pointer\n  TIME: O(n+m) | SPACE: O(1)"},
    9:  {"name":"Linked List Cycle","difficulty":"Easy","topic":"Two Pointers","url":"https://leetcode.com/problems/linked-list-cycle","filename":"linked_list_cycle.py","solution":'''class Solution:\n    def hasCycle(self, head) -> bool:\n        slow = head\n        fast = head\n        while fast and fast.next:\n            slow = slow.next\n            fast = fast.next.next\n            if slow == fast:\n                return True\n        return False''',"explanation":"\n  PATTERN: Floyd's Cycle Detection\n  - Slow moves 1 step, fast moves 2 steps\n  - If cycle exists they will meet!\n  TIME: O(n) | SPACE: O(1)"},
    10: {"name":"Reverse String","difficulty":"Easy","topic":"Two Pointers","url":"https://leetcode.com/problems/reverse-string","filename":"reverse_string.py","solution":'''from typing import List\n\nclass Solution:\n    def reverseString(self, s: List[str]) -> None:\n        left, right = 0, len(s) - 1\n        while left < right:\n            s[left], s[right] = s[right], s[left]\n            left += 1\n            right -= 1''',"explanation":"\n  PATTERN: Two Pointers\n  - Swap from both ends moving inward\n  - Must be done in-place!\n  TIME: O(n) | SPACE: O(1)"},
    11: {"name":"Binary Search","difficulty":"Easy","topic":"Binary Search","url":"https://leetcode.com/problems/binary-search","filename":"binary_search.py","solution":'''from typing import List\n\nclass Solution:\n    def search(self, nums: List[int], target: int) -> int:\n        left, right = 0, len(nums) - 1\n        while left <= right:\n            mid = (left + right) // 2\n            if nums[mid] == target:\n                return mid\n            elif nums[mid] < target:\n                left = mid + 1\n            else:\n                right = mid - 1\n        return -1''',"explanation":"\n  PATTERN: Binary Search\n  - Check middle, eliminate half the array each time\n  TIME: O(log n) | SPACE: O(1)"},
    12: {"name":"Flood Fill","difficulty":"Easy","topic":"BFS/DFS","url":"https://leetcode.com/problems/flood-fill","filename":"flood_fill.py","solution":'''from typing import List\n\nclass Solution:\n    def floodFill(self, image: List[List[int]], sr: int, sc: int, color: int) -> List[List[int]]:\n        original = image[sr][sc]\n        if original == color:\n            return image\n        def dfs(r, c):\n            if r < 0 or r >= len(image) or c < 0 or c >= len(image[0]) or image[r][c] != original:\n                return\n            image[r][c] = color\n            dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\n        dfs(sr, sc)\n        return image''',"explanation":"\n  PATTERN: DFS on Grid\n  - Like paint bucket tool in MS Paint!\n  - Recursively fill all connected same-color pixels\n  TIME: O(n*m) | SPACE: O(n*m)"},
    13: {"name":"Lowest Common Ancestor of BST","difficulty":"Easy","topic":"Binary Search Tree","url":"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree","filename":"lowest_common_ancestor.py","solution":'''class Solution:\n    def lowestCommonAncestor(self, root, p, q):\n        while root:\n            if p.val < root.val and q.val < root.val:\n                root = root.left\n            elif p.val > root.val and q.val > root.val:\n                root = root.right\n            else:\n                return root''',"explanation":"\n  PATTERN: BST Property\n  - Both less than root? Go left\n  - Both greater? Go right\n  - Otherwise? Current node is LCA!\n  TIME: O(h) | SPACE: O(1)"},
    14: {"name":"Balanced Binary Tree","difficulty":"Easy","topic":"Binary Tree","url":"https://leetcode.com/problems/balanced-binary-tree","filename":"balanced_binary_tree.py","solution":'''class Solution:\n    def isBalanced(self, root) -> bool:\n        def height(node):\n            if not node: return 0\n            l = height(node.left)\n            if l == -1: return -1\n            r = height(node.right)\n            if r == -1: return -1\n            if abs(l - r) > 1: return -1\n            return max(l, r) + 1\n        return height(root) != -1''',"explanation":"\n  PATTERN: DFS Recursion\n  - Return -1 if unbalanced, height otherwise\n  TIME: O(n) | SPACE: O(h)"},
    15: {"name":"Diameter of Binary Tree","difficulty":"Easy","topic":"Binary Tree","url":"https://leetcode.com/problems/diameter-of-binary-tree","filename":"diameter_binary_tree.py","solution":'''class Solution:\n    def diameterOfBinaryTree(self, root) -> int:\n        self.res = 0\n        def depth(node):\n            if not node: return 0\n            l = depth(node.left)\n            r = depth(node.right)\n            self.res = max(self.res, l + r)\n            return max(l, r) + 1\n        depth(root)\n        return self.res''',"explanation":"\n  PATTERN: DFS\n  - Diameter at each node = left depth + right depth\n  - Track global max\n  TIME: O(n) | SPACE: O(h)"},
    16: {"name":"Middle of Linked List","difficulty":"Easy","topic":"Linked List","url":"https://leetcode.com/problems/middle-of-the-linked-list","filename":"middle_linked_list.py","solution":'''class Solution:\n    def middleNode(self, head):\n        slow = fast = head\n        while fast and fast.next:\n            slow = slow.next\n            fast = fast.next.next\n        return slow''',"explanation":"\n  PATTERN: Slow & Fast Pointers\n  - When fast reaches end, slow is at middle!\n  TIME: O(n) | SPACE: O(1)"},
    17: {"name":"Maximum Depth of Binary Tree","difficulty":"Easy","topic":"Binary Tree","url":"https://leetcode.com/problems/maximum-depth-of-binary-tree","filename":"max_depth_binary_tree.py","solution":'''class Solution:\n    def maxDepth(self, root) -> int:\n        if not root: return 0\n        return max(self.maxDepth(root.left), self.maxDepth(root.right)) + 1''',"explanation":"\n  PATTERN: DFS Recursion\n  - depth = max(left depth, right depth) + 1\n  TIME: O(n) | SPACE: O(h)"},
    18: {"name":"First Bad Version","difficulty":"Easy","topic":"Binary Search","url":"https://leetcode.com/problems/first-bad-version","filename":"first_bad_version.py","solution":'''class Solution:\n    def firstBadVersion(self, n: int) -> int:\n        left, right = 1, n\n        while left < right:\n            mid = (left + right) // 2\n            if isBadVersion(mid):\n                right = mid\n            else:\n                left = mid + 1\n        return left''',"explanation":"\n  PATTERN: Binary Search\n  - If mid is bad, answer is mid or before → right = mid\n  - If mid is good, answer is after → left = mid+1\n  TIME: O(log n) | SPACE: O(1)"},
    19: {"name":"Ransom Note","difficulty":"Easy","topic":"HashMap","url":"https://leetcode.com/problems/ransom-note","filename":"ransom_note.py","solution":'''from collections import Counter\n\nclass Solution:\n    def canConstruct(self, ransomNote: str, magazine: str) -> bool:\n        mag = Counter(magazine)\n        for c in ransomNote:\n            if mag[c] <= 0: return False\n            mag[c] -= 1\n        return True''',"explanation":"\n  PATTERN: HashMap Counter\n  - Count magazine letters, check if enough for ransom note\n  TIME: O(n+m) | SPACE: O(1)"},
    20: {"name":"Move Zeroes","difficulty":"Easy","topic":"Two Pointers","url":"https://leetcode.com/problems/move-zeroes","filename":"move_zeroes.py","solution":'''from typing import List\n\nclass Solution:\n    def moveZeroes(self, nums: List[int]) -> None:\n        pos = 0\n        for num in nums:\n            if num != 0:\n                nums[pos] = num\n                pos += 1\n        while pos < len(nums):\n            nums[pos] = 0\n            pos += 1''',"explanation":"\n  PATTERN: Two Pointers\n  - Move all non-zeros forward, fill rest with zeros\n  TIME: O(n) | SPACE: O(1)"},
    21: {"name":"Squares of Sorted Array","difficulty":"Easy","topic":"Two Pointers","url":"https://leetcode.com/problems/squares-of-a-sorted-array","filename":"squares_sorted_array.py","solution":'''from typing import List\n\nclass Solution:\n    def sortedSquares(self, nums: List[int]) -> List[int]:\n        res = [0] * len(nums)\n        l, r = 0, len(nums)-1\n        pos = len(nums)-1\n        while l <= r:\n            if abs(nums[l]) > abs(nums[r]):\n                res[pos] = nums[l]**2; l += 1\n            else:\n                res[pos] = nums[r]**2; r -= 1\n            pos -= 1\n        return res''',"explanation":"\n  PATTERN: Two Pointers from both ends\n  - Largest squares come from either end\n  - Fill result from back to front\n  TIME: O(n) | SPACE: O(n)"},
    22: {"name":"Longest Substring Without Repeating","difficulty":"Medium","topic":"Sliding Window","url":"https://leetcode.com/problems/longest-substring-without-repeating-characters","filename":"longest_substring.py","solution":'''class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:\n        char_set = set()\n        left = max_len = 0\n        for right in range(len(s)):\n            while s[right] in char_set:\n                char_set.remove(s[left])\n                left += 1\n            char_set.add(s[right])\n            max_len = max(max_len, right - left + 1)\n        return max_len''',"explanation":"\n  PATTERN: Sliding Window\n  - Expand right, shrink left when duplicate found\n  TIME: O(n) | SPACE: O(n)"},
    23: {"name":"3Sum","difficulty":"Medium","topic":"Two Pointers","url":"https://leetcode.com/problems/3sum","filename":"three_sum.py","solution":'''from typing import List\n\nclass Solution:\n    def threeSum(self, nums: List[int]) -> List[List[int]]:\n        nums.sort()\n        res = []\n        for i in range(len(nums)-2):\n            if i > 0 and nums[i] == nums[i-1]: continue\n            l, r = i+1, len(nums)-1\n            while l < r:\n                s = nums[i]+nums[l]+nums[r]\n                if s == 0:\n                    res.append([nums[i],nums[l],nums[r]])\n                    while l < r and nums[l]==nums[l+1]: l+=1\n                    while l < r and nums[r]==nums[r-1]: r-=1\n                    l+=1; r-=1\n                elif s < 0: l+=1\n                else: r-=1\n        return res''',"explanation":"\n  PATTERN: Sort + Two Pointers\n  - Fix one element, two pointers for the other two\n  - Skip duplicates carefully\n  TIME: O(n^2) | SPACE: O(1)"},
    24: {"name":"Product of Array Except Self","difficulty":"Medium","topic":"Array","url":"https://leetcode.com/problems/product-of-array-except-self","filename":"product_except_self.py","solution":'''from typing import List\n\nclass Solution:\n    def productExceptSelf(self, nums: List[int]) -> List[int]:\n        n = len(nums)\n        res = [1]*n\n        prefix = 1\n        for i in range(n):\n            res[i] = prefix\n            prefix *= nums[i]\n        suffix = 1\n        for i in range(n-1,-1,-1):\n            res[i] *= suffix\n            suffix *= nums[i]\n        return res''',"explanation":"\n  PATTERN: Prefix + Suffix\n  - result[i] = product of all left x product of all right\n  TIME: O(n) | SPACE: O(1)"},
    25: {"name":"Number of Islands","difficulty":"Medium","topic":"BFS/DFS","url":"https://leetcode.com/problems/number-of-islands","filename":"number_of_islands.py","solution":'''from typing import List\n\nclass Solution:\n    def numIslands(self, grid: List[List[str]]) -> int:\n        count = 0\n        def dfs(r,c):\n            if r<0 or r>=len(grid) or c<0 or c>=len(grid[0]) or grid[r][c]!="1": return\n            grid[r][c]="0"\n            dfs(r+1,c);dfs(r-1,c);dfs(r,c+1);dfs(r,c-1)\n        for r in range(len(grid)):\n            for c in range(len(grid[0])):\n                if grid[r][c]=="1":\n                    count+=1\n                    dfs(r,c)\n        return count''',"explanation":"\n  PATTERN: DFS on Grid\n  - Each unvisited 1 is a new island\n  - DFS marks all connected land as visited\n  TIME: O(n*m) | SPACE: O(n*m)"},
    26: {"name":"Coin Change","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/coin-change","filename":"coin_change.py","solution":'''from typing import List\n\nclass Solution:\n    def coinChange(self, coins: List[int], amount: int) -> int:\n        dp = [float("inf")] * (amount + 1)\n        dp[0] = 0\n        for i in range(1, amount + 1):\n            for coin in coins:\n                if coin <= i:\n                    dp[i] = min(dp[i], dp[i - coin] + 1)\n        return dp[amount] if dp[amount] != float("inf") else -1''',"explanation":"\n  PATTERN: Dynamic Programming (Bottom-Up)\n  - dp[i] = minimum coins needed to make amount i\n  - For each amount, try every coin\n  - dp[i] = min(dp[i], dp[i-coin] + 1)\n  TIME: O(amount * coins) | SPACE: O(amount)"},
    27: {"name":"Word Search","difficulty":"Medium","topic":"Backtracking","url":"https://leetcode.com/problems/word-search","filename":"word_search.py","solution":'''from typing import List\n\nclass Solution:\n    def exist(self, board: List[List[str]], word: str) -> bool:\n        rows, cols = len(board), len(board[0])\n        path = set()\n        def dfs(r, c, i):\n            if i == len(word): return True\n            if r<0 or r>=rows or c<0 or c>=cols: return False\n            if board[r][c] != word[i] or (r,c) in path: return False\n            path.add((r,c))\n            res = dfs(r+1,c,i+1) or dfs(r-1,c,i+1) or dfs(r,c+1,i+1) or dfs(r,c-1,i+1)\n            path.remove((r,c))\n            return res\n        for r in range(rows):\n            for c in range(cols):\n                if dfs(r,c,0): return True\n        return False''',"explanation":"\n  PATTERN: Backtracking\n  - Try starting from every cell\n  - DFS to match each character\n  - Mark visited, unmark on backtrack\n  TIME: O(n*m*4^L) | SPACE: O(L)"},
    28: {"name":"Binary Tree Level Order Traversal","difficulty":"Medium","topic":"BFS","url":"https://leetcode.com/problems/binary-tree-level-order-traversal","filename":"binary_tree_level_order.py","solution":'''from typing import List, Optional\nfrom collections import deque\n\nclass Solution:\n    def levelOrder(self, root: Optional[object]) -> List[List[int]]:\n        if not root: return []\n        result = []\n        queue = deque([root])\n        while queue:\n            level = []\n            for _ in range(len(queue)):\n                node = queue.popleft()\n                level.append(node.val)\n                if node.left: queue.append(node.left)\n                if node.right: queue.append(node.right)\n            result.append(level)\n        return result''',"explanation":"\n  PATTERN: BFS with Queue\n  - Process nodes level by level\n  - Use queue size to know when level ends\n  TIME: O(n) | SPACE: O(n)"},
    29: {"name":"Clone Graph","difficulty":"Medium","topic":"Graph","url":"https://leetcode.com/problems/clone-graph","filename":"clone_graph.py","solution":'''from collections import deque\n\nclass Solution:\n    def cloneGraph(self, node):\n        if not node: return None\n        clones = {node: type(node)(node.val)}\n        queue = deque([node])\n        while queue:\n            curr = queue.popleft()\n            for neighbor in curr.neighbors:\n                if neighbor not in clones:\n                    clones[neighbor] = type(neighbor)(neighbor.val)\n                    queue.append(neighbor)\n                clones[curr].neighbors.append(clones[neighbor])\n        return clones[node]''',"explanation":"\n  PATTERN: BFS + HashMap\n  - Use hashmap to map original node to cloned node\n  - BFS to visit all nodes\n  TIME: O(V+E) | SPACE: O(V)"},
    30: {"name":"Max Area of Island","difficulty":"Medium","topic":"BFS/DFS","url":"https://leetcode.com/problems/max-area-of-island","filename":"max_area_island.py","solution":'''from typing import List\n\nclass Solution:\n    def maxAreaOfIsland(self, grid: List[List[int]]) -> int:\n        max_area = 0\n        def dfs(r, c):\n            if r<0 or r>=len(grid) or c<0 or c>=len(grid[0]) or grid[r][c]==0: return 0\n            grid[r][c] = 0\n            return 1 + dfs(r+1,c) + dfs(r-1,c) + dfs(r,c+1) + dfs(r,c-1)\n        for r in range(len(grid)):\n            for c in range(len(grid[0])):\n                if grid[r][c] == 1:\n                    max_area = max(max_area, dfs(r,c))\n        return max_area''',"explanation":"\n  PATTERN: DFS on Grid\n  - DFS returns size of island\n  - Track maximum island size\n  TIME: O(n*m) | SPACE: O(n*m)"},
    31: {"name":"Find Minimum in Rotated Sorted Array","difficulty":"Medium","topic":"Binary Search","url":"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array","filename":"find_minimum_rotated.py","solution":'''from typing import List\n\nclass Solution:\n    def findMin(self, nums: List[int]) -> int:\n        left, right = 0, len(nums) - 1\n        while left < right:\n            mid = (left + right) // 2\n            if nums[mid] > nums[right]:\n                left = mid + 1\n            else:\n                right = mid\n        return nums[left]''',"explanation":"\n  PATTERN: Binary Search on Rotated Array\n  - If mid > right, minimum is in right half\n  - Otherwise minimum is in left half including mid\n  TIME: O(log n) | SPACE: O(1)"},
    32: {"name":"Search in Rotated Sorted Array","difficulty":"Medium","topic":"Binary Search","url":"https://leetcode.com/problems/search-in-rotated-sorted-array","filename":"search_rotated_array.py","solution":'''from typing import List\n\nclass Solution:\n    def search(self, nums: List[int], target: int) -> int:\n        left, right = 0, len(nums) - 1\n        while left <= right:\n            mid = (left + right) // 2\n            if nums[mid] == target: return mid\n            if nums[left] <= nums[mid]:\n                if nums[left] <= target < nums[mid]:\n                    right = mid - 1\n                else:\n                    left = mid + 1\n            else:\n                if nums[mid] < target <= nums[right]:\n                    left = mid + 1\n                else:\n                    right = mid - 1\n        return -1''',"explanation":"\n  PATTERN: Binary Search (Modified)\n  - One half is always sorted\n  - Check if target is in sorted half, adjust accordingly\n  TIME: O(log n) | SPACE: O(1)"},
    33: {"name":"Reorder List","difficulty":"Medium","topic":"Linked List","url":"https://leetcode.com/problems/reorder-list","filename":"reorder_list.py","solution":'''class Solution:\n    def reorderList(self, head) -> None:\n        slow, fast = head, head.next\n        while fast and fast.next:\n            slow = slow.next\n            fast = fast.next.next\n        second = slow.next\n        slow.next = None\n        prev = None\n        while second:\n            tmp = second.next\n            second.next = prev\n            prev = second\n            second = tmp\n        first, second = head, prev\n        while second:\n            tmp1, tmp2 = first.next, second.next\n            first.next = second\n            second.next = tmp1\n            first, second = tmp1, tmp2''',"explanation":"\n  PATTERN: Find Middle + Reverse + Merge\n  - Step 1: Find middle using slow/fast pointers\n  - Step 2: Reverse second half\n  - Step 3: Merge two halves alternately\n  TIME: O(n) | SPACE: O(1)"},
    34: {"name":"Remove Nth Node From End","difficulty":"Medium","topic":"Linked List","url":"https://leetcode.com/problems/remove-nth-node-from-end-of-list","filename":"remove_nth_node.py","solution":'''class Solution:\n    def removeNthFromEnd(self, head, n: int):\n        dummy = type(head)(0)\n        dummy.next = head\n        fast = slow = dummy\n        for _ in range(n + 1):\n            fast = fast.next\n        while fast:\n            fast = fast.next\n            slow = slow.next\n        slow.next = slow.next.next\n        return dummy.next''',"explanation":"\n  PATTERN: Two Pointers with gap\n  - Move fast n+1 steps ahead\n  - Move both until fast is None\n  - slow.next is the node to remove\n  TIME: O(n) | SPACE: O(1)"},
    35: {"name":"Container With Most Water","difficulty":"Medium","topic":"Two Pointers","url":"https://leetcode.com/problems/container-with-most-water","filename":"container_most_water.py","solution":'''from typing import List\n\nclass Solution:\n    def maxArea(self, height: List[int]) -> int:\n        left, right = 0, len(height) - 1\n        max_water = 0\n        while left < right:\n            water = min(height[left], height[right]) * (right - left)\n            max_water = max(max_water, water)\n            if height[left] < height[right]:\n                left += 1\n            else:\n                right -= 1\n        return max_water''',"explanation":"\n  PATTERN: Two Pointers\n  - Water = min(left, right) * width\n  - Move the shorter side inward (greedy)\n  TIME: O(n) | SPACE: O(1)"},
    36: {"name":"Combination Sum","difficulty":"Medium","topic":"Backtracking","url":"https://leetcode.com/problems/combination-sum","filename":"combination_sum.py","solution":'''from typing import List\n\nclass Solution:\n    def combinationSum(self, candidates: List[int], target: int) -> List[List[int]]:\n        res = []\n        def dfs(i, current, total):\n            if total == target:\n                res.append(current[:])\n                return\n            if i >= len(candidates) or total > target:\n                return\n            current.append(candidates[i])\n            dfs(i, current, total + candidates[i])\n            current.pop()\n            dfs(i + 1, current, total)\n        dfs(0, [], 0)\n        return res''',"explanation":"\n  PATTERN: Backtracking\n  - Two choices: include current candidate OR skip it\n  - Can reuse same candidate (pass same index i)\n  TIME: O(2^target) | SPACE: O(target)"},
    37: {"name":"Unique Paths","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/unique-paths","filename":"unique_paths.py","solution":'''class Solution:\n    def uniquePaths(self, m: int, n: int) -> int:\n        dp = [[1] * n for _ in range(m)]\n        for r in range(1, m):\n            for c in range(1, n):\n                dp[r][c] = dp[r-1][c] + dp[r][c-1]\n        return dp[m-1][n-1]''',"explanation":"\n  PATTERN: Dynamic Programming 2D\n  - dp[r][c] = paths from top + paths from left\n  - First row and column are all 1s\n  TIME: O(m*n) | SPACE: O(m*n)"},
    38: {"name":"House Robber","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/house-robber","filename":"house_robber.py","solution":'''from typing import List\n\nclass Solution:\n    def rob(self, nums: List[int]) -> int:\n        prev2, prev1 = 0, 0\n        for num in nums:\n            curr = max(prev1, prev2 + num)\n            prev2 = prev1\n            prev1 = curr\n        return prev1''',"explanation":"\n  PATTERN: Dynamic Programming\n  - At each house: rob it (prev2 + current) OR skip it (prev1)\n  - Take the maximum\n  TIME: O(n) | SPACE: O(1)"},
    39: {"name":"Jump Game","difficulty":"Medium","topic":"Greedy","url":"https://leetcode.com/problems/jump-game","filename":"jump_game.py","solution":'''from typing import List\n\nclass Solution:\n    def canJump(self, nums: List[int]) -> bool:\n        max_reach = 0\n        for i, jump in enumerate(nums):\n            if i > max_reach: return False\n            max_reach = max(max_reach, i + jump)\n        return True''',"explanation":"\n  PATTERN: Greedy\n  - Track maximum reachable index\n  - If current index exceeds max reach, impossible\n  TIME: O(n) | SPACE: O(1)"},
    40: {"name":"Rotate Image","difficulty":"Medium","topic":"Array","url":"https://leetcode.com/problems/rotate-image","filename":"rotate_image.py","solution":'''from typing import List\n\nclass Solution:\n    def rotate(self, matrix: List[List[int]]) -> None:\n        n = len(matrix)\n        for r in range(n):\n            for c in range(r+1, n):\n                matrix[r][c], matrix[c][r] = matrix[c][r], matrix[r][c]\n        for r in range(n):\n            matrix[r].reverse()''',"explanation":"\n  PATTERN: Transpose + Reverse\n  - Step 1: Transpose matrix (swap matrix[r][c] with matrix[c][r])\n  - Step 2: Reverse each row\n  TIME: O(n^2) | SPACE: O(1)"},
    41: {"name":"Group Anagrams","difficulty":"Medium","topic":"HashMap","url":"https://leetcode.com/problems/group-anagrams","filename":"group_anagrams.py","solution":'''from typing import List\nfrom collections import defaultdict\n\nclass Solution:\n    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:\n        anagram_map = defaultdict(list)\n        for s in strs:\n            key = tuple(sorted(s))\n            anagram_map[key].append(s)\n        return list(anagram_map.values())''',"explanation":"\n  PATTERN: HashMap with sorted string as key\n  - Anagrams have same sorted characters\n  - Group by sorted key\n  TIME: O(n*k*log k) | SPACE: O(n*k)"},
    42: {"name":"Top K Frequent Elements","difficulty":"Medium","topic":"Heap","url":"https://leetcode.com/problems/top-k-frequent-elements","filename":"top_k_frequent.py","solution":'''from typing import List\nfrom collections import Counter\n\nclass Solution:\n    def topKFrequent(self, nums: List[int], k: int) -> List[int]:\n        count = Counter(nums)\n        buckets = [[] for _ in range(len(nums) + 1)]\n        for num, freq in count.items():\n            buckets[freq].append(num)\n        result = []\n        for i in range(len(buckets)-1, 0, -1):\n            for num in buckets[i]:\n                result.append(num)\n                if len(result) == k:\n                    return result''',"explanation":"\n  PATTERN: Bucket Sort\n  - Count frequencies\n  - Put numbers in buckets by frequency\n  - Read from highest frequency bucket\n  TIME: O(n) | SPACE: O(n)"},
    43: {"name":"Longest Consecutive Sequence","difficulty":"Medium","topic":"HashSet","url":"https://leetcode.com/problems/longest-consecutive-sequence","filename":"longest_consecutive.py","solution":'''from typing import List\n\nclass Solution:\n    def longestConsecutive(self, nums: List[int]) -> int:\n        num_set = set(nums)\n        max_len = 0\n        for num in num_set:\n            if num - 1 not in num_set:\n                length = 1\n                while num + length in num_set:\n                    length += 1\n                max_len = max(max_len, length)\n        return max_len''',"explanation":"\n  PATTERN: HashSet\n  - Only start counting from sequence start (num-1 not in set)\n  - Count consecutive numbers forward\n  TIME: O(n) | SPACE: O(n)"},
    44: {"name":"Valid Sudoku","difficulty":"Medium","topic":"Array","url":"https://leetcode.com/problems/valid-sudoku","filename":"valid_sudoku.py","solution":'''from typing import List\nfrom collections import defaultdict\n\nclass Solution:\n    def isValidSudoku(self, board: List[List[str]]) -> bool:\n        rows = defaultdict(set)\n        cols = defaultdict(set)\n        boxes = defaultdict(set)\n        for r in range(9):\n            for c in range(9):\n                val = board[r][c]\n                if val == ".": continue\n                box = (r//3, c//3)\n                if val in rows[r] or val in cols[c] or val in boxes[box]:\n                    return False\n                rows[r].add(val)\n                cols[c].add(val)\n                boxes[box].add(val)\n        return True''',"explanation":"\n  PATTERN: HashSet for rows, cols, boxes\n  - Check each number against its row, column, and 3x3 box\n  - box key = (r//3, c//3)\n  TIME: O(1) fixed 9x9 | SPACE: O(1)"},
    45: {"name":"Spiral Matrix","difficulty":"Medium","topic":"Array","url":"https://leetcode.com/problems/spiral-matrix","filename":"spiral_matrix.py","solution":'''from typing import List\n\nclass Solution:\n    def spiralOrder(self, matrix: List[List[int]]) -> List[int]:\n        res = []\n        top, bottom = 0, len(matrix)-1\n        left, right = 0, len(matrix[0])-1\n        while top <= bottom and left <= right:\n            for c in range(left, right+1): res.append(matrix[top][c])\n            top += 1\n            for r in range(top, bottom+1): res.append(matrix[r][right])\n            right -= 1\n            if top <= bottom:\n                for c in range(right, left-1, -1): res.append(matrix[bottom][c])\n                bottom -= 1\n            if left <= right:\n                for r in range(bottom, top-1, -1): res.append(matrix[r][left])\n                left += 1\n        return res''',"explanation":"\n  PATTERN: Layer by layer with 4 boundaries\n  - top, bottom, left, right boundaries\n  - Shrink boundaries after each direction\n  TIME: O(n*m) | SPACE: O(1)"},
    46: {"name":"Set Matrix Zeroes","difficulty":"Medium","topic":"Array","url":"https://leetcode.com/problems/set-matrix-zeroes","filename":"set_matrix_zeroes.py","solution":'''from typing import List\n\nclass Solution:\n    def setZeroes(self, matrix: List[List[int]]) -> None:\n        rows, cols = set(), set()\n        for r in range(len(matrix)):\n            for c in range(len(matrix[0])):\n                if matrix[r][c] == 0:\n                    rows.add(r)\n                    cols.add(c)\n        for r in range(len(matrix)):\n            for c in range(len(matrix[0])):\n                if r in rows or c in cols:\n                    matrix[r][c] = 0''',"explanation":"\n  PATTERN: Mark rows and cols first\n  - First pass: record which rows and cols have zeros\n  - Second pass: zero out those rows and cols\n  TIME: O(n*m) | SPACE: O(n+m)"},
    47: {"name":"Pacific Atlantic Water Flow","difficulty":"Medium","topic":"BFS/DFS","url":"https://leetcode.com/problems/pacific-atlantic-water-flow","filename":"pacific_atlantic.py","solution":'''from typing import List\nfrom collections import deque\n\nclass Solution:\n    def pacificAtlantic(self, heights: List[List[int]]) -> List[List[int]]:\n        rows, cols = len(heights), len(heights[0])\n        pac, atl = set(), set()\n        def bfs(starts, visited):\n            queue = deque(starts)\n            visited.update(starts)\n            while queue:\n                r, c = queue.popleft()\n                for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n                    nr, nc = r+dr, c+dc\n                    if 0<=nr<rows and 0<=nc<cols and (nr,nc) not in visited and heights[nr][nc]>=heights[r][c]:\n                        visited.add((nr,nc))\n                        queue.append((nr,nc))\n        bfs([(r,0) for r in range(rows)]+[(0,c) for c in range(cols)], pac)\n        bfs([(r,cols-1) for r in range(rows)]+[(rows-1,c) for c in range(cols)], atl)\n        return [[r,c] for r in range(rows) for c in range(cols) if (r,c) in pac and (r,c) in atl]''',"explanation":"\n  PATTERN: Reverse BFS from ocean borders\n  - BFS from Pacific border cells\n  - BFS from Atlantic border cells\n  - Answer = cells reachable from BOTH\n  TIME: O(n*m) | SPACE: O(n*m)"},
    48: {"name":"Course Schedule","difficulty":"Medium","topic":"Graph","url":"https://leetcode.com/problems/course-schedule","filename":"course_schedule.py","solution":'''from typing import List\nfrom collections import defaultdict\n\nclass Solution:\n    def canFinish(self, numCourses: int, prerequisites: List[List[int]]) -> bool:\n        graph = defaultdict(list)\n        for a, b in prerequisites:\n            graph[a].append(b)\n        visited = set()\n        def dfs(node):\n            if node in visited: return False\n            if graph[node] == []: return True\n            visited.add(node)\n            for nei in graph[node]:\n                if not dfs(nei): return False\n            visited.remove(node)\n            graph[node] = []\n            return True\n        for c in range(numCourses):\n            if not dfs(c): return False\n        return True''',"explanation":"\n  PATTERN: Cycle Detection in Directed Graph\n  - Build adjacency list\n  - DFS to detect cycles\n  - If cycle found, cannot finish all courses\n  TIME: O(V+E) | SPACE: O(V+E)"},
    49: {"name":"House Robber II","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/house-robber-ii","filename":"house_robber_2.py","solution":'''from typing import List\n\nclass Solution:\n    def rob(self, nums: List[int]) -> int:\n        if len(nums) == 1: return nums[0]\n        def rob_linear(houses):\n            prev2, prev1 = 0, 0\n            for num in houses:\n                curr = max(prev1, prev2 + num)\n                prev2, prev1 = prev1, curr\n            return prev1\n        return max(rob_linear(nums[:-1]), rob_linear(nums[1:]))''',"explanation":"\n  PATTERN: DP - Run twice, skip one end\n  - Houses in circle: first and last cannot both be robbed\n  - Run House Robber I on nums[:-1] and nums[1:]\n  - Take maximum of both\n  TIME: O(n) | SPACE: O(1)"},
    50: {"name":"Longest Palindromic Substring","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/longest-palindromic-substring","filename":"longest_palindrome.py","solution":'''class Solution:\n    def longestPalindrome(self, s: str) -> str:\n        res = ""\n        def expand(l, r):\n            nonlocal res\n            while l >= 0 and r < len(s) and s[l] == s[r]:\n                if r - l + 1 > len(res):\n                    res = s[l:r+1]\n                l -= 1\n                r += 1\n        for i in range(len(s)):\n            expand(i, i)\n            expand(i, i+1)\n        return res''',"explanation":"\n  PATTERN: Expand Around Center\n  - For each character, expand outward checking palindrome\n  - Check both odd (i,i) and even (i,i+1) centers\n  TIME: O(n^2) | SPACE: O(1)"},

    # ── NEW PROBLEMS 51–100 ──────────────────────────────────────────────────

    51: {"name":"Min Stack","difficulty":"Medium","topic":"Stack","url":"https://leetcode.com/problems/min-stack","filename":"min_stack.py","solution":'''class MinStack:\n    def __init__(self):\n        self.stack = []\n        self.min_stack = []\n\n    def push(self, val: int) -> None:\n        self.stack.append(val)\n        min_val = min(val, self.min_stack[-1] if self.min_stack else val)\n        self.min_stack.append(min_val)\n\n    def pop(self) -> None:\n        self.stack.pop()\n        self.min_stack.pop()\n\n    def top(self) -> int:\n        return self.stack[-1]\n\n    def getMin(self) -> int:\n        return self.min_stack[-1]''',"explanation":"\n  PATTERN: Parallel Stack\n  - Maintain a second stack that always stores current minimum\n  - push: append min(new_val, current_min) to min_stack\n  - pop: pop both stacks together\n  TIME: O(1) all ops | SPACE: O(n)"},

    52: {"name":"Daily Temperatures","difficulty":"Medium","topic":"Monotonic Stack","url":"https://leetcode.com/problems/daily-temperatures","filename":"daily_temperatures.py","solution":'''from typing import List\n\nclass Solution:\n    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:\n        res = [0] * len(temperatures)\n        stack = []  # stores indices\n        for i, temp in enumerate(temperatures):\n            while stack and temp > temperatures[stack[-1]]:\n                idx = stack.pop()\n                res[idx] = i - idx\n            stack.append(i)\n        return res''',"explanation":"\n  PATTERN: Monotonic Decreasing Stack\n  - Stack stores indices of unresolved days\n  - When we find a warmer day, resolve all cooler days in stack\n  TIME: O(n) | SPACE: O(n)"},

    53: {"name":"Car Fleet","difficulty":"Medium","topic":"Monotonic Stack","url":"https://leetcode.com/problems/car-fleet","filename":"car_fleet.py","solution":'''from typing import List\n\nclass Solution:\n    def carFleet(self, target: int, position: List[int], speed: List[int]) -> int:\n        pairs = sorted(zip(position, speed), reverse=True)\n        stack = []\n        for pos, spd in pairs:\n            time = (target - pos) / spd\n            stack.append(time)\n            if len(stack) >= 2 and stack[-1] <= stack[-2]:\n                stack.pop()  # caught up, same fleet\n        return len(stack)''',"explanation":"\n  PATTERN: Monotonic Stack (sorted by position)\n  - Sort cars by starting position (closest to target first)\n  - Compute time each car takes to reach target\n  - If a car arrives <= the car ahead, they merge into one fleet\n  TIME: O(n log n) | SPACE: O(n)"},

    54: {"name":"Evaluate Reverse Polish Notation","difficulty":"Medium","topic":"Stack","url":"https://leetcode.com/problems/evaluate-reverse-polish-notation","filename":"evaluate_rpn.py","solution":'''from typing import List\n\nclass Solution:\n    def evalRPN(self, tokens: List[str]) -> int:\n        stack = []\n        ops = {"+", "-", "*", "/"}\n        for t in tokens:\n            if t in ops:\n                b, a = stack.pop(), stack.pop()\n                if t == "+": stack.append(a + b)\n                elif t == "-": stack.append(a - b)\n                elif t == "*": stack.append(a * b)\n                else: stack.append(int(a / b))  # truncate toward zero\n            else:\n                stack.append(int(t))\n        return stack[0]''',"explanation":"\n  PATTERN: Stack\n  - Push numbers onto stack\n  - On operator: pop two, compute, push result\n  - Use int(a/b) not a//b for correct negative truncation\n  TIME: O(n) | SPACE: O(n)"},

    55: {"name":"Kth Largest Element in Array","difficulty":"Medium","topic":"Heap","url":"https://leetcode.com/problems/kth-largest-element-in-an-array","filename":"kth_largest.py","solution":'''from typing import List\nimport heapq\n\nclass Solution:\n    def findKthLargest(self, nums: List[int], k: int) -> int:\n        min_heap = []\n        for num in nums:\n            heapq.heappush(min_heap, num)\n            if len(min_heap) > k:\n                heapq.heappop(min_heap)\n        return min_heap[0]''',"explanation":"\n  PATTERN: Min-Heap of size k\n  - Keep a min-heap with only k elements\n  - The root is always the kth largest\n  - If heap exceeds k, pop the minimum\n  TIME: O(n log k) | SPACE: O(k)"},

    56: {"name":"Task Scheduler","difficulty":"Medium","topic":"Heap/Greedy","url":"https://leetcode.com/problems/task-scheduler","filename":"task_scheduler.py","solution":'''from typing import List\nfrom collections import Counter\nimport heapq\nfrom collections import deque\n\nclass Solution:\n    def leastInterval(self, tasks: List[str], n: int) -> int:\n        count = Counter(tasks)\n        max_heap = [-c for c in count.values()]\n        heapq.heapify(max_heap)\n        time = 0\n        queue = deque()  # (count, available_at)\n        while max_heap or queue:\n            time += 1\n            if max_heap:\n                cnt = 1 + heapq.heappop(max_heap)\n                if cnt: queue.append((cnt, time + n))\n            if queue and queue[0][1] == time:\n                heapq.heappush(max_heap, queue.popleft()[0])\n        return time''',"explanation":"\n  PATTERN: Max-Heap + Cooldown Queue\n  - Always process the most frequent task available\n  - Track cooldown with a queue of (count, available_at)\n  TIME: O(n log n) | SPACE: O(n)"},

    57: {"name":"Design Twitter","difficulty":"Medium","topic":"Heap/OOP","url":"https://leetcode.com/problems/design-twitter","filename":"design_twitter.py","solution":'''import heapq\nfrom collections import defaultdict\n\nclass Twitter:\n    def __init__(self):\n        self.count = 0\n        self.tweets = defaultdict(list)  # userId -> [(timestamp, tweetId)]\n        self.following = defaultdict(set)\n\n    def postTweet(self, userId: int, tweetId: int) -> None:\n        self.tweets[userId].append((self.count, tweetId))\n        self.count -= 1  # lower = more recent for min-heap trick\n\n    def getNewsFeed(self, userId: int) -> list:\n        min_heap = []\n        self.following[userId].add(userId)\n        for uid in self.following[userId]:\n            if uid in self.tweets:\n                idx = len(self.tweets[uid]) - 1\n                cnt, tid = self.tweets[uid][idx]\n                heapq.heappush(min_heap, (cnt, tid, uid, idx - 1))\n        res = []\n        while min_heap and len(res) < 10:\n            cnt, tid, uid, idx = heapq.heappop(min_heap)\n            res.append(tid)\n            if idx >= 0:\n                cnt2, tid2 = self.tweets[uid][idx]\n                heapq.heappush(min_heap, (cnt2, tid2, uid, idx - 1))\n        return res\n\n    def follow(self, f, fd): self.following[f].add(fd)\n    def unfollow(self, f, fd): self.following[f].discard(fd)''',"explanation":"\n  PATTERN: Heap Merge (k sorted lists)\n  - Merge tweet streams from all followed users\n  - Use min-heap with negative timestamp as 'priority'\n  TIME: getNewsFeed O(k log k) | SPACE: O(n)"},

    58: {"name":"Subsets","difficulty":"Medium","topic":"Backtracking","url":"https://leetcode.com/problems/subsets","filename":"subsets.py","solution":'''from typing import List\n\nclass Solution:\n    def subsets(self, nums: List[int]) -> List[List[int]]:\n        res = []\n        def dfs(i, subset):\n            if i == len(nums):\n                res.append(subset[:])\n                return\n            subset.append(nums[i])   # include\n            dfs(i + 1, subset)\n            subset.pop()             # exclude\n            dfs(i + 1, subset)\n        dfs(0, [])\n        return res''',"explanation":"\n  PATTERN: Backtracking (Include/Exclude)\n  - For each element: include it OR exclude it\n  - Total 2^n subsets\n  TIME: O(2^n) | SPACE: O(n)"},

    59: {"name":"Permutations","difficulty":"Medium","topic":"Backtracking","url":"https://leetcode.com/problems/permutations","filename":"permutations.py","solution":'''from typing import List\n\nclass Solution:\n    def permute(self, nums: List[int]) -> List[List[int]]:\n        res = []\n        def dfs(current, remaining):\n            if not remaining:\n                res.append(current[:])\n                return\n            for i in range(len(remaining)):\n                current.append(remaining[i])\n                dfs(current, remaining[:i] + remaining[i+1:])\n                current.pop()\n        dfs([], nums)\n        return res''',"explanation":"\n  PATTERN: Backtracking\n  - At each step, pick any unused number\n  - Recurse with remaining numbers\n  TIME: O(n * n!) | SPACE: O(n)"},

    60: {"name":"Letter Combinations of Phone Number","difficulty":"Medium","topic":"Backtracking","url":"https://leetcode.com/problems/letter-combinations-of-a-phone-number","filename":"letter_combinations.py","solution":'''from typing import List\n\nclass Solution:\n    def letterCombinations(self, digits: str) -> List[str]:\n        if not digits: return []\n        phone = {"2":"abc","3":"def","4":"ghi","5":"jkl","6":"mno","7":"pqrs","8":"tuv","9":"wxyz"}\n        res = []\n        def dfs(i, current):\n            if i == len(digits):\n                res.append(current)\n                return\n            for c in phone[digits[i]]:\n                dfs(i + 1, current + c)\n        dfs(0, "")\n        return res''',"explanation":"\n  PATTERN: Backtracking\n  - Map each digit to its letters\n  - At each position, try all letters for that digit\n  TIME: O(4^n * n) | SPACE: O(n)"},

    61: {"name":"Subarray Sum Equals K","difficulty":"Medium","topic":"Prefix Sum + HashMap","url":"https://leetcode.com/problems/subarray-sum-equals-k","filename":"subarray_sum_k.py","solution":'''from typing import List\nfrom collections import defaultdict\n\nclass Solution:\n    def subarraySum(self, nums: List[int], k: int) -> int:\n        count = 0\n        prefix = 0\n        seen = defaultdict(int)\n        seen[0] = 1\n        for num in nums:\n            prefix += num\n            count += seen[prefix - k]\n            seen[prefix] += 1\n        return count''',"explanation":"\n  PATTERN: Prefix Sum + HashMap\n  - If prefix[j] - prefix[i] == k, then subarray i+1..j sums to k\n  - Store how many times each prefix sum has occurred\n  TIME: O(n) | SPACE: O(n)"},

    62: {"name":"Minimum Window Substring","difficulty":"Hard","topic":"Sliding Window","url":"https://leetcode.com/problems/minimum-window-substring","filename":"min_window_substring.py","solution":'''from collections import Counter\n\nclass Solution:\n    def minWindow(self, s: str, t: str) -> str:\n        if not t: return ""\n        need = Counter(t)\n        have, want = 0, len(need)\n        window = {}\n        res, res_len = [-1, -1], float("inf")\n        left = 0\n        for right, c in enumerate(s):\n            window[c] = window.get(c, 0) + 1\n            if c in need and window[c] == need[c]:\n                have += 1\n            while have == want:\n                if right - left + 1 < res_len:\n                    res = [left, right]\n                    res_len = right - left + 1\n                window[s[left]] -= 1\n                if s[left] in need and window[s[left]] < need[s[left]]:\n                    have -= 1\n                left += 1\n        l, r = res\n        return s[l:r+1] if res_len != float("inf") else ""''',"explanation":"\n  PATTERN: Sliding Window (two counters)\n  - have = chars satisfied, want = distinct chars needed\n  - Expand right until all satisfied, shrink left to minimize\n  TIME: O(n) | SPACE: O(n)"},

    63: {"name":"Trapping Rain Water","difficulty":"Hard","topic":"Two Pointers","url":"https://leetcode.com/problems/trapping-rain-water","filename":"trapping_rain_water.py","solution":'''from typing import List\n\nclass Solution:\n    def trap(self, height: List[int]) -> int:\n        left, right = 0, len(height) - 1\n        left_max = right_max = 0\n        water = 0\n        while left < right:\n            if height[left] < height[right]:\n                if height[left] >= left_max:\n                    left_max = height[left]\n                else:\n                    water += left_max - height[left]\n                left += 1\n            else:\n                if height[right] >= right_max:\n                    right_max = height[right]\n                else:\n                    water += right_max - height[right]\n                right -= 1\n        return water''',"explanation":"\n  PATTERN: Two Pointers\n  - Water at position i = min(max_left, max_right) - height[i]\n  - Move the shorter side inward, accumulating water\n  TIME: O(n) | SPACE: O(1)"},

    64: {"name":"Sliding Window Maximum","difficulty":"Hard","topic":"Monotonic Deque","url":"https://leetcode.com/problems/sliding-window-maximum","filename":"sliding_window_max.py","solution":'''from typing import List\nfrom collections import deque\n\nclass Solution:\n    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:\n        dq = deque()  # indices, decreasing values\n        res = []\n        left = 0\n        for right in range(len(nums)):\n            while dq and nums[dq[-1]] <= nums[right]:\n                dq.pop()\n            dq.append(right)\n            if dq[0] < left:\n                dq.popleft()\n            if right >= k - 1:\n                res.append(nums[dq[0]])\n                left += 1\n        return res''',"explanation":"\n  PATTERN: Monotonic Decreasing Deque\n  - Deque front = index of max element in window\n  - Remove from back if smaller than new element\n  - Remove from front if out of window\n  TIME: O(n) | SPACE: O(k)"},

    65: {"name":"Median of Two Sorted Arrays","difficulty":"Hard","topic":"Binary Search","url":"https://leetcode.com/problems/median-of-two-sorted-arrays","filename":"median_two_sorted.py","solution":'''from typing import List\n\nclass Solution:\n    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:\n        A, B = nums1, nums2\n        if len(A) > len(B): A, B = B, A\n        total = len(A) + len(B)\n        half = total // 2\n        left, right = 0, len(A) - 1\n        while True:\n            i = (left + right) // 2\n            j = half - i - 2\n            Aleft  = A[i] if i >= 0 else float("-inf")\n            Aright = A[i+1] if i+1 < len(A) else float("inf")\n            Bleft  = B[j] if j >= 0 else float("-inf")\n            Bright = B[j+1] if j+1 < len(B) else float("inf")\n            if Aleft <= Bright and Bleft <= Aright:\n                if total % 2:\n                    return min(Aright, Bright)\n                return (max(Aleft, Bleft) + min(Aright, Bright)) / 2\n            elif Aleft > Bright:\n                right = i - 1\n            else:\n                left = i + 1''',"explanation":"\n  PATTERN: Binary Search on partition\n  - Binary search on the smaller array\n  - Find partition where left half <= right half across both arrays\n  TIME: O(log min(n,m)) | SPACE: O(1)"},

    66: {"name":"Find Median from Data Stream","difficulty":"Hard","topic":"Two Heaps","url":"https://leetcode.com/problems/find-median-from-data-stream","filename":"find_median_stream.py","solution":'''import heapq\n\nclass MedianFinder:\n    def __init__(self):\n        self.small = []  # max-heap (negate values)\n        self.large = []  # min-heap\n\n    def addNum(self, num: int) -> None:\n        heapq.heappush(self.small, -num)\n        if self.small and self.large and -self.small[0] > self.large[0]:\n            heapq.heappush(self.large, -heapq.heappop(self.small))\n        if len(self.small) > len(self.large) + 1:\n            heapq.heappush(self.large, -heapq.heappop(self.small))\n        if len(self.large) > len(self.small):\n            heapq.heappush(self.small, -heapq.heappop(self.large))\n\n    def findMedian(self) -> float:\n        if len(self.small) > len(self.large):\n            return -self.small[0]\n        return (-self.small[0] + self.large[0]) / 2''',"explanation":"\n  PATTERN: Two Heaps (max-heap + min-heap)\n  - small (max-heap): lower half | large (min-heap): upper half\n  - Keep sizes balanced: |small| == |large| or |small| == |large|+1\n  - Median = top of small (odd) or avg of tops (even)\n  TIME: O(log n) add | O(1) find | SPACE: O(n)"},

    67: {"name":"Merge K Sorted Lists","difficulty":"Hard","topic":"Heap","url":"https://leetcode.com/problems/merge-k-sorted-lists","filename":"merge_k_sorted.py","solution":'''from typing import List, Optional\nimport heapq\n\nclass Solution:\n    def mergeKLists(self, lists: List[Optional[object]]) -> Optional[object]:\n        heap = []\n        for i, node in enumerate(lists):\n            if node:\n                heapq.heappush(heap, (node.val, i, node))\n        dummy = type(lists[0])(0) if lists and lists[0] else None\n        if not dummy: return None\n        curr = dummy\n        while heap:\n            val, i, node = heapq.heappop(heap)\n            curr.next = node\n            curr = curr.next\n            if node.next:\n                heapq.heappush(heap, (node.next.val, i, node.next))\n        return dummy.next''',"explanation":"\n  PATTERN: Min-Heap (Priority Queue)\n  - Push head of each list into heap\n  - Always extract minimum, push next node from that list\n  - Use list index as tiebreaker\n  TIME: O(n log k) | SPACE: O(k)"},

    68: {"name":"Reverse Nodes in K-Group","difficulty":"Hard","topic":"Linked List","url":"https://leetcode.com/problems/reverse-nodes-in-k-group","filename":"reverse_k_group.py","solution":'''class Solution:\n    def reverseKGroup(self, head, k: int):\n        dummy = type(head)(0)\n        dummy.next = head\n        group_prev = dummy\n        while True:\n            kth = self.get_kth(group_prev, k)\n            if not kth: break\n            group_next = kth.next\n            prev, curr = kth.next, group_prev.next\n            while curr != group_next:\n                tmp = curr.next\n                curr.next = prev\n                prev = curr\n                curr = tmp\n            tmp = group_prev.next\n            group_prev.next = kth\n            group_prev = tmp\n        return dummy.next\n\n    def get_kth(self, curr, k):\n        while curr and k > 0:\n            curr = curr.next\n            k -= 1\n        return curr''',"explanation":"\n  PATTERN: Group Reversal\n  - Find kth node from current position\n  - Reverse that group, connect to previous group\n  - Repeat for next group\n  TIME: O(n) | SPACE: O(1)"},

    69: {"name":"LRU Cache","difficulty":"Medium","topic":"Design + HashMap + DLL","url":"https://leetcode.com/problems/lru-cache","filename":"lru_cache.py","solution":'''class Node:\n    def __init__(self, key=0, val=0):\n        self.key, self.val = key, val\n        self.prev = self.next = None\n\nclass LRUCache:\n    def __init__(self, capacity: int):\n        self.cap = capacity\n        self.cache = {}\n        self.left = Node()  # LRU end (dummy)\n        self.right = Node() # MRU end (dummy)\n        self.left.next = self.right\n        self.right.prev = self.left\n\n    def remove(self, node):\n        node.prev.next, node.next.prev = node.next, node.prev\n\n    def insert(self, node):  # insert at MRU end\n        prev, nxt = self.right.prev, self.right\n        prev.next = nxt.prev = node\n        node.prev, node.next = prev, nxt\n\n    def get(self, key: int) -> int:\n        if key in self.cache:\n            self.remove(self.cache[key])\n            self.insert(self.cache[key])\n            return self.cache[key].val\n        return -1\n\n    def put(self, key: int, value: int) -> None:\n        if key in self.cache:\n            self.remove(self.cache[key])\n        self.cache[key] = Node(key, value)\n        self.insert(self.cache[key])\n        if len(self.cache) > self.cap:\n            lru = self.left.next\n            self.remove(lru)\n            del self.cache[lru.key]''',"explanation":"\n  PATTERN: HashMap + Doubly Linked List\n  - HashMap for O(1) access\n  - DLL for O(1) insert/remove (MRU at right, LRU at left)\n  - On get/put: move node to MRU end\n  - On overflow: remove LRU node (left.next)\n  TIME: O(1) get/put | SPACE: O(capacity)"},

    70: {"name":"Word Break","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/word-break","filename":"word_break.py","solution":'''from typing import List\n\nclass Solution:\n    def wordBreak(self, s: str, wordDict: List[str]) -> bool:\n        words = set(wordDict)\n        dp = [False] * (len(s) + 1)\n        dp[0] = True\n        for i in range(1, len(s) + 1):\n            for j in range(i):\n                if dp[j] and s[j:i] in words:\n                    dp[i] = True\n                    break\n        return dp[len(s)]''',"explanation":"\n  PATTERN: Dynamic Programming\n  - dp[i] = True if s[:i] can be segmented using wordDict\n  - dp[i] = any dp[j] and s[j:i] in words\n  TIME: O(n^2 * m) | SPACE: O(n)"},

    71: {"name":"Decode Ways","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/decode-ways","filename":"decode_ways.py","solution":'''class Solution:\n    def numDecodings(self, s: str) -> int:\n        if s[0] == "0": return 0\n        dp = [0] * (len(s) + 1)\n        dp[0] = 1\n        dp[1] = 1\n        for i in range(2, len(s) + 1):\n            if s[i-1] != "0":\n                dp[i] += dp[i-1]\n            two_digit = int(s[i-2:i])\n            if 10 <= two_digit <= 26:\n                dp[i] += dp[i-2]\n        return dp[len(s)]''',"explanation":"\n  PATTERN: Dynamic Programming\n  - dp[i] = ways to decode s[:i]\n  - Single digit: if s[i-1] != '0', add dp[i-1]\n  - Two digits: if 10-26, add dp[i-2]\n  TIME: O(n) | SPACE: O(n)"},

    72: {"name":"Partition Equal Subset Sum","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/partition-equal-subset-sum","filename":"partition_equal_subset.py","solution":'''from typing import List\n\nclass Solution:\n    def canPartition(self, nums: List[int]) -> bool:\n        total = sum(nums)\n        if total % 2 != 0: return False\n        target = total // 2\n        dp = {0}\n        for num in nums:\n            dp = {s + num for s in dp} | dp\n            if target in dp: return True\n        return False''',"explanation":"\n  PATTERN: 0/1 Knapsack (Set DP)\n  - Check if we can reach exactly target = sum/2\n  - dp = set of all achievable sums so far\n  - For each num, extend all existing sums\n  TIME: O(n * target) | SPACE: O(target)"},

    73: {"name":"Target Sum","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/target-sum","filename":"target_sum.py","solution":'''from typing import List\nfrom collections import defaultdict\n\nclass Solution:\n    def findTargetSumWays(self, nums: List[int], target: int) -> int:\n        dp = defaultdict(int)\n        dp[0] = 1\n        for num in nums:\n            next_dp = defaultdict(int)\n            for s, count in dp.items():\n                next_dp[s + num] += count\n                next_dp[s - num] += count\n            dp = next_dp\n        return dp[target]''',"explanation":"\n  PATTERN: DP with HashMap (count of ways)\n  - At each num, either add or subtract it\n  - dp[sum] = number of ways to reach that sum\n  TIME: O(n * total_sum) | SPACE: O(total_sum)"},

    74: {"name":"Longest Common Subsequence","difficulty":"Medium","topic":"Dynamic Programming","url":"https://leetcode.com/problems/longest-common-subsequence","filename":"longest_common_subsequence.py","solution":'''class Solution:\n    def longestCommonSubsequence(self, text1: str, text2: str) -> int:\n        m, n = len(text1), len(text2)\n        dp = [[0] * (n + 1) for _ in range(m + 1)]\n        for i in range(1, m + 1):\n            for j in range(1, n + 1):\n                if text1[i-1] == text2[j-1]:\n                    dp[i][j] = 1 + dp[i-1][j-1]\n                else:\n                    dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n        return dp[m][n]''',"explanation":"\n  PATTERN: 2D Dynamic Programming\n  - dp[i][j] = LCS of text1[:i] and text2[:j]\n  - Match: dp[i][j] = 1 + dp[i-1][j-1]\n  - No match: dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n  TIME: O(m*n) | SPACE: O(m*n)"},

    75: {"name":"Edit Distance","difficulty":"Hard","topic":"Dynamic Programming","url":"https://leetcode.com/problems/edit-distance","filename":"edit_distance.py","solution":'''class Solution:\n    def minDistance(self, word1: str, word2: str) -> int:\n        m, n = len(word1), len(word2)\n        dp = [[0] * (n + 1) for _ in range(m + 1)]\n        for i in range(m + 1): dp[i][0] = i\n        for j in range(n + 1): dp[0][j] = j\n        for i in range(1, m + 1):\n            for j in range(1, n + 1):\n                if word1[i-1] == word2[j-1]:\n                    dp[i][j] = dp[i-1][j-1]\n                else:\n                    dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n        return dp[m][n]''',"explanation":"\n  PATTERN: 2D DP (insert, delete, replace)\n  - dp[i][j] = min edits to convert word1[:i] to word2[:j]\n  - Match: no edit needed\n  - Mismatch: 1 + min(delete, insert, replace)\n  TIME: O(m*n) | SPACE: O(m*n)"},

    76: {"name":"Distinct Subsequences","difficulty":"Hard","topic":"Dynamic Programming","url":"https://leetcode.com/problems/distinct-subsequences","filename":"distinct_subsequences.py","solution":'''class Solution:\n    def numDistinct(self, s: str, t: str) -> int:\n        m, n = len(s), len(t)\n        dp = [[0] * (n + 1) for _ in range(m + 1)]\n        for i in range(m + 1): dp[i][0] = 1\n        for i in range(1, m + 1):\n            for j in range(1, n + 1):\n                dp[i][j] = dp[i-1][j]\n                if s[i-1] == t[j-1]:\n                    dp[i][j] += dp[i-1][j-1]\n        return dp[m][n]''',"explanation":"\n  PATTERN: 2D DP\n  - dp[i][j] = # of ways to form t[:j] from s[:i]\n  - Always carry forward dp[i-1][j] (skip s[i])\n  - If chars match, also add dp[i-1][j-1] (use s[i])\n  TIME: O(m*n) | SPACE: O(m*n)"},

    77: {"name":"Burst Balloons","difficulty":"Hard","topic":"Dynamic Programming (Interval)","url":"https://leetcode.com/problems/burst-balloons","filename":"burst_balloons.py","solution":'''from typing import List\n\nclass Solution:\n    def maxCoins(self, nums: List[int]) -> int:\n        nums = [1] + nums + [1]\n        n = len(nums)\n        dp = [[0] * n for _ in range(n)]\n        for length in range(2, n):\n            for left in range(0, n - length):\n                right = left + length\n                for k in range(left + 1, right):\n                    dp[left][right] = max(\n                        dp[left][right],\n                        nums[left] * nums[k] * nums[right] + dp[left][k] + dp[k][right]\n                    )\n        return dp[0][n-1]''',"explanation":"\n  PATTERN: Interval DP (think in reverse — last balloon to burst)\n  - Add boundary 1s to handle edges\n  - dp[left][right] = max coins in open interval (left, right)\n  - k = last balloon to burst in this interval\n  TIME: O(n^3) | SPACE: O(n^2)"},

    78: {"name":"Regular Expression Matching","difficulty":"Hard","topic":"Dynamic Programming","url":"https://leetcode.com/problems/regular-expression-matching","filename":"regex_matching.py","solution":'''class Solution:\n    def isMatch(self, s: str, p: str) -> bool:\n        m, n = len(s), len(p)\n        dp = [[False] * (n + 1) for _ in range(m + 1)]\n        dp[0][0] = True\n        for j in range(1, n + 1):\n            if p[j-1] == "*":\n                dp[0][j] = dp[0][j-2]\n        for i in range(1, m + 1):\n            for j in range(1, n + 1):\n                if p[j-1] == "*":\n                    dp[i][j] = dp[i][j-2]  # zero occurrences\n                    if p[j-2] == "." or p[j-2] == s[i-1]:\n                        dp[i][j] = dp[i][j] or dp[i-1][j]  # one+ occurrences\n                elif p[j-1] == "." or p[j-1] == s[i-1]:\n                    dp[i][j] = dp[i-1][j-1]\n        return dp[m][n]''',"explanation":"\n  PATTERN: 2D DP with star handling\n  - dp[i][j] = s[:i] matches p[:j]\n  - '.' matches any char\n  - 'x*' = zero (use dp[i][j-2]) or one+ of x (use dp[i-1][j])\n  TIME: O(m*n) | SPACE: O(m*n)"},

    79: {"name":"Number of 1 Bits","difficulty":"Easy","topic":"Bit Manipulation","url":"https://leetcode.com/problems/number-of-1-bits","filename":"number_of_1_bits.py","solution":'''class Solution:\n    def hammingWeight(self, n: int) -> int:\n        count = 0\n        while n:\n            n &= n - 1  # remove lowest set bit\n            count += 1\n        return count''',"explanation":"\n  PATTERN: Bit Manipulation (Brian Kernighan)\n  - n & (n-1) clears the lowest set bit\n  - Count how many times until n = 0\n  TIME: O(k) k=number of 1 bits | SPACE: O(1)"},

    80: {"name":"Counting Bits","difficulty":"Easy","topic":"Bit Manipulation","url":"https://leetcode.com/problems/counting-bits","filename":"counting_bits.py","solution":'''from typing import List\n\nclass Solution:\n    def countBits(self, n: int) -> List[int]:\n        dp = [0] * (n + 1)\n        for i in range(1, n + 1):\n            dp[i] = dp[i >> 1] + (i & 1)\n        return dp''',"explanation":"\n  PATTERN: DP + Bit Trick\n  - dp[i] = dp[i//2] + (1 if i is odd else 0)\n  - i>>1 shifts right = divide by 2 (removes last bit)\n  - (i&1) = last bit (0 or 1)\n  TIME: O(n) | SPACE: O(n)"},

    81: {"name":"Reverse Bits","difficulty":"Easy","topic":"Bit Manipulation","url":"https://leetcode.com/problems/reverse-bits","filename":"reverse_bits.py","solution":'''class Solution:\n    def reverseBits(self, n: int) -> int:\n        result = 0\n        for _ in range(32):\n            result = (result << 1) | (n & 1)\n            n >>= 1\n        return result''',"explanation":"\n  PATTERN: Bit-by-bit extraction\n  - Extract last bit of n with (n & 1)\n  - Shift result left and OR in extracted bit\n  - Do 32 times for 32-bit integer\n  TIME: O(1) | SPACE: O(1)"},

    82: {"name":"Missing Number","difficulty":"Easy","topic":"Bit Manipulation","url":"https://leetcode.com/problems/missing-number","filename":"missing_number.py","solution":'''from typing import List\n\nclass Solution:\n    def missingNumber(self, nums: List[int]) -> int:\n        return len(nums) * (len(nums) + 1) // 2 - sum(nums)''',"explanation":"\n  PATTERN: Gauss Formula\n  - Expected sum = n*(n+1)/2\n  - Missing = expected - actual sum\n  TIME: O(n) | SPACE: O(1)"},

    83: {"name":"Sum of Two Integers","difficulty":"Medium","topic":"Bit Manipulation","url":"https://leetcode.com/problems/sum-of-two-integers","filename":"sum_two_integers.py","solution":'''class Solution:\n    def getSum(self, a: int, b: int) -> int:\n        mask = 0xFFFFFFFF\n        while b & mask:\n            carry = (a & b) << 1\n            a = a ^ b\n            b = carry\n        return a if b == 0 else a & mask''',"explanation":"\n  PATTERN: Bit Manipulation (no + operator)\n  - XOR = addition without carry\n  - AND << 1 = carry\n  - Repeat until no carry; mask for Python's infinite integers\n  TIME: O(1) | SPACE: O(1)"},

    84: {"name":"Number of Connected Components","difficulty":"Medium","topic":"Union Find","url":"https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph","filename":"connected_components.py","solution":'''from typing import List\n\nclass Solution:\n    def countComponents(self, n: int, edges: List[List[int]]) -> int:\n        parent = list(range(n))\n        rank = [1] * n\n\n        def find(x):\n            while parent[x] != x:\n                parent[x] = parent[parent[x]]  # path compression\n                x = parent[x]\n            return x\n\n        def union(x, y):\n            px, py = find(x), find(y)\n            if px == py: return 0\n            if rank[px] < rank[py]: px, py = py, px\n            parent[py] = px\n            rank[px] += rank[py]\n            return 1\n\n        return n - sum(union(u, v) for u, v in edges)''',"explanation":"\n  PATTERN: Union Find\n  - Start with n components\n  - Each successful union reduces count by 1\n  - Path compression + union by rank for efficiency\n  TIME: O(n * alpha(n)) ≈ O(n) | SPACE: O(n)"},

    85: {"name":"Redundant Connection","difficulty":"Medium","topic":"Union Find","url":"https://leetcode.com/problems/redundant-connection","filename":"redundant_connection.py","solution":'''from typing import List\n\nclass Solution:\n    def findRedundantConnection(self, edges: List[List[int]]) -> List[int]:\n        parent = list(range(len(edges) + 1))\n        rank = [1] * (len(edges) + 1)\n\n        def find(x):\n            while parent[x] != x:\n                parent[x] = parent[parent[x]]\n                x = parent[x]\n            return x\n\n        def union(x, y):\n            px, py = find(x), find(y)\n            if px == py: return False\n            if rank[px] < rank[py]: px, py = py, px\n            parent[py] = px\n            rank[px] += rank[py]\n            return True\n\n        for u, v in edges:\n            if not union(u, v):\n                return [u, v]''',"explanation":"\n  PATTERN: Union Find (detect cycle)\n  - Add edges one by one\n  - If two nodes already connected (same root), this edge is redundant\n  TIME: O(n * alpha(n)) | SPACE: O(n)"},

    86: {"name":"Graph Valid Tree","difficulty":"Medium","topic":"Union Find / BFS","url":"https://leetcode.com/problems/graph-valid-tree","filename":"graph_valid_tree.py","solution":'''from typing import List\n\nclass Solution:\n    def validTree(self, n: int, edges: List[List[int]]) -> bool:\n        if len(edges) != n - 1: return False\n        parent = list(range(n))\n\n        def find(x):\n            while parent[x] != x:\n                parent[x] = parent[parent[x]]\n                x = parent[x]\n            return x\n\n        def union(x, y):\n            px, py = find(x), find(y)\n            if px == py: return False\n            parent[px] = py\n            return True\n\n        return all(union(u, v) for u, v in edges)''',"explanation":"\n  PATTERN: Union Find\n  - Tree = connected + no cycles\n  - n-1 edges required (quick check)\n  - Union each edge; if any creates cycle → not a tree\n  TIME: O(n) | SPACE: O(n)"},

    87: {"name":"Course Schedule II","difficulty":"Medium","topic":"Topological Sort","url":"https://leetcode.com/problems/course-schedule-ii","filename":"course_schedule_2.py","solution":'''from typing import List\nfrom collections import defaultdict, deque\n\nclass Solution:\n    def findOrder(self, numCourses: int, prerequisites: List[List[int]]) -> List[int]:\n        graph = defaultdict(list)\n        in_degree = [0] * numCourses\n        for a, b in prerequisites:\n            graph[b].append(a)\n            in_degree[a] += 1\n        queue = deque([i for i in range(numCourses) if in_degree[i] == 0])\n        order = []\n        while queue:\n            node = queue.popleft()\n            order.append(node)\n            for nei in graph[node]:\n                in_degree[nei] -= 1\n                if in_degree[nei] == 0:\n                    queue.append(nei)\n        return order if len(order) == numCourses else []''',"explanation":"\n  PATTERN: Topological Sort (Kahn's BFS)\n  - in_degree = number of prerequisites for each course\n  - Start with courses that have 0 prerequisites\n  - Process, reduce in_degrees, add new 0s to queue\n  TIME: O(V+E) | SPACE: O(V+E)"},

    88: {"name":"Alien Dictionary","difficulty":"Hard","topic":"Topological Sort","url":"https://leetcode.com/problems/alien-dictionary","filename":"alien_dictionary.py","solution":'''from typing import List\nfrom collections import defaultdict, deque\n\nclass Solution:\n    def alienOrder(self, words: List[str]) -> str:\n        adj = {c: set() for w in words for c in w}\n        for i in range(len(words) - 1):\n            w1, w2 = words[i], words[i+1]\n            min_len = min(len(w1), len(w2))\n            if len(w1) > len(w2) and w1[:min_len] == w2[:min_len]:\n                return ""\n            for j in range(min_len):\n                if w1[j] != w2[j]:\n                    adj[w1[j]].add(w2[j])\n                    break\n        visited = {}  # False=visited, True=in_cycle\n        res = []\n        def dfs(c):\n            if c in visited: return visited[c]\n            visited[c] = True\n            for nei in adj[c]:\n                if dfs(nei): return True\n            visited[c] = False\n            res.append(c)\n        for c in adj:\n            if dfs(c): return ""\n        res.reverse()\n        return "".join(res)''',"explanation":"\n  PATTERN: Topological Sort (DFS)\n  - Extract ordering rules by comparing adjacent words\n  - DFS topo sort; detect cycles\n  TIME: O(C) C=total characters | SPACE: O(1) (26 chars max)"},

    89: {"name":"Network Delay Time","difficulty":"Medium","topic":"Dijkstra / Graph","url":"https://leetcode.com/problems/network-delay-time","filename":"network_delay.py","solution":'''from typing import List\nimport heapq\nfrom collections import defaultdict\n\nclass Solution:\n    def networkDelayTime(self, times: List[List[int]], n: int, k: int) -> int:\n        graph = defaultdict(list)\n        for u, v, w in times:\n            graph[u].append((v, w))\n        dist = {}\n        heap = [(0, k)]  # (cost, node)\n        while heap:\n            cost, u = heapq.heappop(heap)\n            if u in dist: continue\n            dist[u] = cost\n            for v, w in graph[u]:\n                if v not in dist:\n                    heapq.heappush(heap, (cost + w, v))\n        return max(dist.values()) if len(dist) == n else -1''',"explanation":"\n  PATTERN: Dijkstra's Algorithm\n  - Shortest path from source k to all nodes\n  - Min-heap: always process the nearest unvisited node\n  - Answer = max of all shortest distances\n  TIME: O(E log V) | SPACE: O(V+E)"},

    90: {"name":"Cheapest Flights K Stops","difficulty":"Medium","topic":"Bellman-Ford / Graph","url":"https://leetcode.com/problems/cheapest-flights-within-k-stops","filename":"cheapest_flights.py","solution":'''from typing import List\n\nclass Solution:\n    def findCheapestPrice(self, n: int, flights: List[List[int]], src: int, dst: int, k: int) -> int:\n        prices = [float("inf")] * n\n        prices[src] = 0\n        for _ in range(k + 1):  # k stops = k+1 edges\n            tmp = prices.copy()\n            for u, v, w in flights:\n                if prices[u] != float("inf") and prices[u] + w < tmp[v]:\n                    tmp[v] = prices[u] + w\n            prices = tmp\n        return prices[dst] if prices[dst] != float("inf") else -1''',"explanation":"\n  PATTERN: Bellman-Ford (relaxed to k+1 iterations)\n  - Run k+1 rounds of edge relaxation\n  - Use a copy to prevent using same edge twice in one round\n  TIME: O(k * E) | SPACE: O(n)"},

    91: {"name":"Swim in Rising Water","difficulty":"Hard","topic":"Dijkstra / Binary Search","url":"https://leetcode.com/problems/swim-in-rising-water","filename":"swim_rising_water.py","solution":'''from typing import List\nimport heapq\n\nclass Solution:\n    def swimInWater(self, grid: List[List[int]]) -> int:\n        n = len(grid)\n        visited = set()\n        heap = [(grid[0][0], 0, 0)]  # (max_elevation, r, c)\n        dirs = [(1,0),(-1,0),(0,1),(0,-1)]\n        while heap:\n            t, r, c = heapq.heappop(heap)\n            if (r, c) in visited: continue\n            visited.add((r, c))\n            if r == n-1 and c == n-1: return t\n            for dr, dc in dirs:\n                nr, nc = r+dr, c+dc\n                if 0<=nr<n and 0<=nc<n and (nr,nc) not in visited:\n                    heapq.heappush(heap, (max(t, grid[nr][nc]), nr, nc))''',"explanation":"\n  PATTERN: Dijkstra (minimize maximum elevation)\n  - Heap stores (max_elevation_seen, r, c)\n  - Greedily pick path that minimizes the maximum elevation\n  TIME: O(n^2 log n) | SPACE: O(n^2)"},

    92: {"name":"Reconstruct Itinerary","difficulty":"Hard","topic":"Graph / Euler Path","url":"https://leetcode.com/problems/reconstruct-itinerary","filename":"reconstruct_itinerary.py","solution":'''from typing import List\nfrom collections import defaultdict\n\nclass Solution:\n    def findItinerary(self, tickets: List[List[str]]) -> List[str]:\n        graph = defaultdict(list)\n        for src, dst in sorted(tickets, reverse=True):\n            graph[src].append(dst)\n        res = []\n        def dfs(airport):\n            while graph[airport]:\n                dfs(graph[airport].pop())\n            res.append(airport)\n        dfs("JFK")\n        return res[::-1]''',"explanation":"\n  PATTERN: Hierholzer's Algorithm (Euler Path)\n  - Sort destinations in reverse so pop() gives lexical order\n  - Post-order DFS: append to result AFTER all neighbors visited\n  - Reverse at end\n  TIME: O(E log E) | SPACE: O(E)"},

    93: {"name":"Implement Trie","difficulty":"Medium","topic":"Trie","url":"https://leetcode.com/problems/implement-trie-prefix-tree","filename":"trie.py","solution":'''class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.end = False\n\nclass Trie:\n    def __init__(self):\n        self.root = TrieNode()\n\n    def insert(self, word: str) -> None:\n        curr = self.root\n        for c in word:\n            if c not in curr.children:\n                curr.children[c] = TrieNode()\n            curr = curr.children[c]\n        curr.end = True\n\n    def search(self, word: str) -> bool:\n        curr = self.root\n        for c in word:\n            if c not in curr.children: return False\n            curr = curr.children[c]\n        return curr.end\n\n    def startsWith(self, prefix: str) -> bool:\n        curr = self.root\n        for c in prefix:\n            if c not in curr.children: return False\n            curr = curr.children[c]\n        return True''',"explanation":"\n  PATTERN: Trie (Prefix Tree)\n  - Each node has a dict of children and an end flag\n  - Insert: create nodes for each character\n  - Search: traverse; check end flag\n  - startsWith: traverse; just check if path exists\n  TIME: O(n) each op | SPACE: O(ALPHABET_SIZE * n)"},

    94: {"name":"Design Add and Search Words","difficulty":"Medium","topic":"Trie + DFS","url":"https://leetcode.com/problems/design-add-and-search-words-data-structure","filename":"add_search_words.py","solution":'''class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.end = False\n\nclass WordDictionary:\n    def __init__(self):\n        self.root = TrieNode()\n\n    def addWord(self, word: str) -> None:\n        curr = self.root\n        for c in word:\n            if c not in curr.children:\n                curr.children[c] = TrieNode()\n            curr = curr.children[c]\n        curr.end = True\n\n    def search(self, word: str) -> bool:\n        def dfs(j, node):\n            for i in range(j, len(word)):\n                c = word[i]\n                if c == ".":\n                    return any(dfs(i+1, child) for child in node.children.values())\n                if c not in node.children:\n                    return False\n                node = node.children[c]\n            return node.end\n        return dfs(0, self.root)''',"explanation":"\n  PATTERN: Trie + DFS for wildcards\n  - '.' can match any character → try all children with DFS\n  - Exact char → go to that child\n  TIME: O(M) insert, O(M*26^M) worst search | SPACE: O(n)"},

    95: {"name":"Word Search II","difficulty":"Hard","topic":"Trie + Backtracking","url":"https://leetcode.com/problems/word-search-ii","filename":"word_search_2.py","solution":'''from typing import List\n\nclass TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.word = None\n\nclass Solution:\n    def findWords(self, board: List[List[str]], words: List[str]) -> List[str]:\n        root = TrieNode()\n        for w in words:\n            curr = root\n            for c in w:\n                if c not in curr.children:\n                    curr.children[c] = TrieNode()\n                curr = curr.children[c]\n            curr.word = w\n        rows, cols = len(board), len(board[0])\n        res = []\n        def dfs(r, c, node):\n            ch = board[r][c]\n            if ch not in node.children: return\n            next_node = node.children[ch]\n            if next_node.word:\n                res.append(next_node.word)\n                next_node.word = None  # avoid duplicates\n            board[r][c] = "#"\n            for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n                nr, nc = r+dr, c+dc\n                if 0<=nr<rows and 0<=nc<cols and board[nr][nc] != "#":\n                    dfs(nr, nc, next_node)\n            board[r][c] = ch\n        for r in range(rows):\n            for c in range(cols):\n                dfs(r, c, root)\n        return res''',"explanation":"\n  PATTERN: Trie + Backtracking\n  - Build trie from all words\n  - DFS on board guided by trie (prune early if prefix not in trie)\n  - Set word=None after finding to avoid duplicates\n  TIME: O(M*N*4*3^(L-1)) | SPACE: O(total_chars)"},

    96: {"name":"N Queens","difficulty":"Hard","topic":"Backtracking","url":"https://leetcode.com/problems/n-queens","filename":"n_queens.py","solution":'''from typing import List\n\nclass Solution:\n    def solveNQueens(self, n: int) -> List[List[str]]:\n        cols = set()\n        pos_diag = set()  # r + c\n        neg_diag = set()  # r - c\n        board = [["."]*n for _ in range(n)]\n        res = []\n        def dfs(r):\n            if r == n:\n                res.append(["".join(row) for row in board])\n                return\n            for c in range(n):\n                if c in cols or r+c in pos_diag or r-c in neg_diag:\n                    continue\n                cols.add(c); pos_diag.add(r+c); neg_diag.add(r-c)\n                board[r][c] = "Q"\n                dfs(r + 1)\n                cols.remove(c); pos_diag.remove(r+c); neg_diag.remove(r-c)\n                board[r][c] = "."\n        dfs(0)\n        return res''',"explanation":"\n  PATTERN: Backtracking with constraint sets\n  - Place one queen per row; track col, pos_diag, neg_diag conflicts\n  - pos_diag: r+c same | neg_diag: r-c same\n  TIME: O(n!) | SPACE: O(n^2)"},

    97: {"name":"Largest Rectangle in Histogram","difficulty":"Hard","topic":"Monotonic Stack","url":"https://leetcode.com/problems/largest-rectangle-in-histogram","filename":"largest_rectangle.py","solution":'''from typing import List\n\nclass Solution:\n    def largestRectangleArea(self, heights: List[int]) -> int:\n        max_area = 0\n        stack = []  # (start_index, height)\n        for i, h in enumerate(heights):\n            start = i\n            while stack and stack[-1][1] > h:\n                idx, height = stack.pop()\n                max_area = max(max_area, height * (i - idx))\n                start = idx\n            stack.append((start, h))\n        for i, h in stack:\n            max_area = max(max_area, h * (len(heights) - i))\n        return max_area''',"explanation":"\n  PATTERN: Monotonic Increasing Stack\n  - For each bar: pop taller bars, compute their max rectangle\n  - start = leftmost index this height could extend to\n  TIME: O(n) | SPACE: O(n)"},

    98: {"name":"Maximum Profit in Job Scheduling","difficulty":"Hard","topic":"DP + Binary Search","url":"https://leetcode.com/problems/maximum-profit-in-job-scheduling","filename":"job_scheduling.py","solution":'''from typing import List\nimport bisect\n\nclass Solution:\n    def jobScheduling(self, startTime: List[int], endTime: List[int], profit: List[int]) -> int:\n        jobs = sorted(zip(startTime, endTime, profit), key=lambda x: x[1])\n        dp = [(0, 0)]  # (end_time, max_profit)\n        for s, e, p in jobs:\n            i = bisect.bisect_right(dp, (s, float("inf"))) - 1\n            best = dp[i][1] + p\n            if best > dp[-1][1]:\n                dp.append((e, best))\n        return dp[-1][1]''',"explanation":"\n  PATTERN: DP + Binary Search\n  - Sort by end time\n  - dp = [(end_time, max_profit)] (non-decreasing profit)\n  - For each job: binary search latest non-overlapping job\n  - Only append if we improve profit\n  TIME: O(n log n) | SPACE: O(n)"},

    99: {"name":"Count of Smaller Numbers After Self","difficulty":"Hard","topic":"Merge Sort / Fenwick Tree","url":"https://leetcode.com/problems/count-of-smaller-numbers-after-self","filename":"count_smaller.py","solution":'''from typing import List\n\nclass Solution:\n    def countSmaller(self, nums: List[int]) -> List[int]:\n        result = [0] * len(nums)\n        indices = list(range(len(nums)))\n\n        def merge_sort(idx):\n            if len(idx) <= 1: return idx\n            mid = len(idx) // 2\n            left = merge_sort(idx[:mid])\n            right = merge_sort(idx[mid:])\n            merged = []\n            r = 0\n            for l_idx in left:\n                while r < len(right) and nums[right[r]] < nums[l_idx]:\n                    r += 1\n                result[l_idx] += r\n                merged.append(l_idx)\n            return merged + right\n\n        merge_sort(indices)\n        return result''',"explanation":"\n  PATTERN: Modified Merge Sort\n  - During merge: count how many right-side elements move past each left element\n  - Those are all smaller numbers that appear to the right!\n  TIME: O(n log n) | SPACE: O(n)"},

    100: {"name":"Serialize and Deserialize Binary Tree","difficulty":"Hard","topic":"Tree + BFS","url":"https://leetcode.com/problems/serialize-and-deserialize-binary-tree","filename":"serialize_binary_tree.py","solution":'''from collections import deque\n\nclass Codec:\n    def serialize(self, root) -> str:\n        if not root: return ""\n        res = []\n        queue = deque([root])\n        while queue:\n            node = queue.popleft()\n            if node:\n                res.append(str(node.val))\n                queue.append(node.left)\n                queue.append(node.right)\n            else:\n                res.append("N")\n        return ",".join(res)\n\n    def deserialize(self, data: str):\n        if not data: return None\n        vals = data.split(",")\n        # Use a placeholder class — works with any TreeNode-like object\n        class N:\n            def __init__(self, v): self.val=v; self.left=self.right=None\n        root = N(int(vals[0]))\n        queue = deque([root])\n        i = 1\n        while queue:\n            node = queue.popleft()\n            if vals[i] != "N":\n                node.left = N(int(vals[i]))\n                queue.append(node.left)\n            i += 1\n            if vals[i] != "N":\n                node.right = N(int(vals[i]))\n                queue.append(node.right)\n            i += 1\n        return root''',"explanation":"\n  PATTERN: BFS Level-Order Serialization\n  - Serialize: BFS, mark None as 'N'\n  - Deserialize: BFS, rebuild level by level\n  - Each non-null node has exactly 2 slots in the next level\n  TIME: O(n) | SPACE: O(n)"},
}


def load_progress():
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE,'r') as f:
            return json.load(f)
    return {"completed_days":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],"start_date":"2026-04-27"}

def save_progress(p):
    with open(PROGRESS_FILE,'w') as f:
        json.dump(p,f,indent=2)

def get_today_day(p):
    c = p["completed_days"]
    return max(c)+1 if c else 1

def calculate_streak(p):
    if not p["completed_days"]: return 0
    c = sorted(p["completed_days"])
    s = 1
    for i in range(len(c)-1,0,-1):
        if c[i]-c[i-1]==1: s+=1
        else: break
    return s

def show_notification(title, msg):
    try:
        subprocess.run(['powershell','-Command',f'Add-Type -AssemblyName System.Windows.Forms; $n=New-Object System.Windows.Forms.NotifyIcon; $n.Icon=[System.Drawing.SystemIcons]::Information; $n.Visible=$true; $n.ShowBalloonTip(8000,"{title}","{msg}",[System.Windows.Forms.ToolTipIcon]::Info); Start-Sleep 3; $n.Dispose()'],capture_output=True)
    except: pass

def show_solution(prob):
    print("\n"+"="*55)
    print(f"  SOLUTION: {prob['name']}")
    print("="*55)
    print(f"\n  EXPLANATION:{prob['explanation']}")
    print(f"\n  CODE:")
    print("  "+"-"*50)
    for line in prob['solution'].split('\\n'):
        print(f"  {line}")
    print("  "+"-"*50)
    print("\n  TYPE this on LeetCode - don't copy paste!")
    print("="*55)

def save_and_push(day, prob, progress):
    filepath = os.path.join(DSA_FOLDER, prob['filename'])
    content = f"# Day {day}: {prob['name']}\n# Difficulty: {prob['difficulty']}\n# Topic: {prob['topic']}\n# Date: {datetime.date.today()}\n\n{prob['solution'].replace(chr(92)+'n', chr(10))}\n"
    with open(filepath,'w') as f:
        f.write(content)
    print(f"  Saved: {prob['filename']}")
    subprocess.run(['code', filepath], capture_output=True, shell=True)
    with open(README_PATH,'r') as f:
        content = f.read()
    new_row = f"| {day} | {prob['name']} | {prob['difficulty']} | {prob['topic']} |"
    if new_row not in content:
        lines = content.split('\n')
        last = -1
        for i,line in enumerate(lines):
            if line.startswith('|') and any(c.isdigit() for c in line.split('|')[1] if line.count('|')>2):
                last = i
        if last > 0:
            lines.insert(last+1, new_row)
            with open(README_PATH,'w') as f:
                f.write('\n'.join(lines))
            print(f"  README updated!")
    try:
        os.chdir(DSA_FOLDER)
        subprocess.run(['git','add','.'],check=True)
        r = subprocess.run(['git','commit','-m',f'Day {day}: Solved {prob["name"]}'],capture_output=True,text=True)
        if 'nothing to commit' not in r.stdout:
            subprocess.run(['git','push','origin','master'],check=True)
            print(f"  Pushed to GitHub!")
        else:
            print("  Already up to date")
    except Exception as e:
        print(f"  Git error: {e}\n  Run: git pull origin master")
    if day not in progress["completed_days"]:
        progress["completed_days"].append(day)
        save_progress(progress)
    streak = calculate_streak(progress)
    print(f"\n  Day {day} COMPLETE! Streak: {streak} days!")
    print("  green " * min(streak,15))
    show_notification(f"Day {day} Complete!",f"Streak: {streak} days!")

def show_progress(p):
    done = len(p["completed_days"])
    streak = calculate_streak(p)
    pct = int((done/150)*100)
    bar = "X"*(pct//5)+"_"*(20-pct//5)
    print(f"\n  Solved: {done}/150 | Streak: {streak} days | [{bar}] {pct}%")

def main():
    print("\n  SHESHANDRA'S DAILY LEETCODE TRACKER")
    print("  Target: Google ML Engineer 2028")
    progress = load_progress()
    day = get_today_day(progress)
    if day not in PROBLEMS:
        print(f"\n  Day {day} not added yet! Ask Claude to add more problems!")
        return
    prob = PROBLEMS[day]
    show_notification(f"Day {day} LeetCode!", f"{prob['name']} ({prob['difficulty']})")
    while True:
        print(f"\n  DAY {day}: {prob['name']} | {prob['difficulty']} | {prob['topic']}")
        print(f"  {prob['url']}")
        print("  [1] Open LeetCode  [2] Show Solution  [3] Save+Push  [4] Progress  [5] Exit")
        choice = input("  Choice: ").strip()
        if choice=='1':
            webbrowser.open(prob['url'])
        elif choice=='2':
            show_solution(prob)
        elif choice=='3':
            save_and_push(day, prob, progress)
        elif choice=='4':
            show_progress(progress)
        elif choice=='5':
            print("  See you tomorrow!")
            break
        else:
            print("  Enter 1-5!")

if __name__=="__main__":
    main()